#!/bin/bash

lerna version 1.0.0 --no-commit-hooks --no-git-tag-version --yes

#npx lerna exec --concurrency 1 --no-sort --stream -- \
#  conventional-changelog \
#    --preset angular \
#    --infile CHANGELOG.md \
#    --same-file \
#    --release-count 0 \
#    --lerna-package \$LERNA_PACKAGE_NAME \
#    --commit-path \$PWD
