#!/bin/bash

npx lerna exec --concurrency 1 --stream -- \
  conventional-recommended-bump \
    --preset angular \
    --lerna-package \$LERNA_PACKAGE_NAME \
    --commit-path \$PWD

# npx lerna exec --concurrency 1 --no-sort --stream -- \
#  conventional-changelog \
#    --preset angular \
#    --infile CHANGELOG.md \
#    --same-file \
#    --release-count 0 \
#    --lerna-package \$LERNA_PACKAGE_NAME \
#    --commit-path \$PWD
